name: Trigger auto deployment for ca-rf-dev-uks-01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-rf-dev-uks-01-AutoDeployTrigger-1c59915f-45ba-4df4-879f-82929b7715cb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CARFDEVUKS01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CARFDEVUKS01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CARFDEVUKS01_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CARFDEVUKS01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CARFDEVUKS01_REGISTRY_PASSWORD }}
          containerAppName: ca-rf-dev-uks-01
          resourceGroup: rg-rf-dev-uks-01
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


